### ISSUE TITLE
Merge WordPress 5.0 in the 1.0 version

### ISSUE THREAD

**Issue by markkap** [calmPress/calmpress#149]
Most likely this is going to be mostly about removing gutenberg :(, but there might still be some worthwhile modification.

Should be done when 5.0 is finally available.

**Comment by stefanos82** [comment]
Which parts of WordPress do you plan to merge with cP?

**Comment by markkap** [comment]
Probably almost nothing, but it is better to merge often to keep the GIT history in sync otherwise when you want to merge later you get hard to resolve merge conflicts.

From the actual code POV, I will need to look at what is the recommended way to detect gutenberg and classic editor, and how 2019 handles it, and make sure that the relevant APIs will work for calmPress and report "classic" all the time. This is for theme and plugin compatibility.

**Comment by stefanos82** [comment]
In other words, calmPress is a stripped down version of WordPress?

I thought this fork would follow a different direction than WordPress's.

**Comment by markkap** [comment]
Yes, it is going to be a CMS oriented and developer and site admin
friendly, not a web based front page replacement aimed at people that miss
the good old days of geocities :)
Definitely not just a stripped down version of WordPress, but stripping
down is a must as there is no way to move forward with the legacy baggage
WordPress carries.

**Comment by stefanos82** [comment]
That's good to know.
