### ISSUE TITLE
Remove dead code that is executed only for unsupported server configuration

### ISSUE THREAD

**Issue by markkap** [calmPress/calmpress#155]
Prime example is code to be run for PHP earlier of 7.0, but there might be other examples

**Comment by markkap** [comment]
Skipping PHPmailer, see #159

**Comment by markkap** [comment]
Skipping text_diff. the library is not supported anymore and we need to be thankful it works at all

**Comment by mikeschinkel** [comment]
Where are the _"supported server configurations"_ documented?
