### ISSUE TITLE
Upgrade jQuery to the latest stable version

### ISSUE THREAD

**Issue by markkap** [calmPress/calmpress#157]
Currently jQuery is at version 3 while calmPress still uses version 1.

**Comment by stefanos82** [comment]
Any plans to replace it with vanilla JS?

**Comment by markkap** [comment]
I wish, but I do not think it is a realistic goal, unless there will be someone that hate jQuery with passion that will volunteer to do it ;). 

You are just not going to gain much from eliminating one http request on the admin side. It is a much more worthy goal on a client side, but there it is up to theme and plugin authors to start using vanilla JS.

**Comment by stefanos82** [comment]
Hmm...I see. Oh well, maybe in the near future, it can be done bit by bit.

**Comment by markkap** [comment]
Yes, hopefully new code will use only vanilla, but to convert all the code will take years.

**Comment by stefanos82** [comment]
It could if this change would be made by a single individual.

The more hands though the faster it will get there.

Oh well, time will tell.

**Comment by markkap** [comment]
Well, wordpress core had started to use 3.6 in 5.8 or before, and plans to upgrade the jquery-ui library as well in 5.9. 1.0.0 Is going to be based on wordpress 5.9, so nothing realy left to do here.
