### ISSUE TITLE
Failed opening required: autoloader.php

### ISSUE THREAD

**Issue by mitchelldmiller** [calmPress/calmpress#224]
I installed latest release from `1.0.0-alpha8.tar.gz`.

> Failed opening required '/wp-includes/calmpress/autoloader.php

Release contained directory 'calmPress' but wp-settings wanted 'calmpress'.

Edited [wp-settings.php](https://github.com/calmPress/calmpress/blob/cp/1.0/src/wp-settings.php#L247) to fix.

**Comment by markkap** [comment]
Thanks were actually already fixed and I thought I have updated alpha 8 with it. serves me right for developing on windows ;)
