### ISSUE TITLE
no css loaded in admin

### ISSUE THREAD

**Issue by unclescooby** [calmPress/calmpress#258]
load-styles.php is empty making admin completely useless. Query monitor shows for most styles it fetches minimized css files, but there are none...

Version: 1.0.0 alpha14
Tested with fresh install and migration on localhost (xampp/windows)

**Comment by markkap** [comment]
Thanks @unclescooby for the report,
Any chance you can check for PHP errors? 
What is the setup, root directory or subdirectory?
Anything special at all about the setting?

**Comment by unclescooby** [comment]
I'm not seeing any php errors in the output or via query monitor. WP_DEBUG is enabled. There's no php log file.

The setup:

- xampp for windows 7.2.0 / PHP 7.2.0
- using testcalmpress.loc domainname, set via windows hosts file pointing to 127.0.0.1
- files are in htdocs/testcalmpress.loc/ folder Vhosts config:
```
<VirtualHost *:80>
DocumentRoot "C:/xampp720/htdocs/testcalmpress.loc"
ServerName testcalmpress.loc
ServerAlias *.testcalmpress.loc
   <Directory "C:/xampp720/htdocs/testcalmpress.loc">
      Order allow,deny
      Allow from all
   </Directory>
</VirtualHost>
```
- apache access log shows 404's like `"GET /wp-includes/css/editor.min.css?ver=xxxxxxxxxx HTTP/1.1" 404 81332 "http://testcalmpress.loc/wp-admin/"  ......`

**Comment by unclescooby** [comment]
Any feedback from your end would be appreciated. You removed the minimized css files, so is calmpress supposed to load the non-minimized files? Or is it supposed to generate minimized files itself. Or ..... ?

**Comment by markkap** [comment]
Sorry, busy offline life caused unhappy clients that I had to satisfy first before reading properly your previous post.

One of the differences between calmPress and WordPress is that WordPress has a weird version number that can be used to indicate a development version and once detected, force some areas of the code to be in "debug mode". In calmPress it is reduced to look at the value of WP_DEBUG.

Now what you see is probably a result of a build problem that does not create and/or package correctly minified files. I noticed that WordPress changed their build process in 5.1 or 5.2 and currently the build process of calmPress is out of sync with it which might be the reason for what you see.

Still in a "make clients happy" mode, so will take me another day or two to check if my assumption is correct (already changed the build process, but need some mental bandwidth to properly test this aspect)

**Comment by markkap** [comment]
@unclescooby Had verified that my suspicion is correct. I will probably release alpha-15 during the week to fix it (will take time as the plugin screen right now is a little too much in flux for even an alpha release)

**Comment by markkap** [comment]
@unclescooby, Took more time ( as always :( ) but here is alpha-15 https://downloads.calmpress.org/1.0.0-alpha15-full.zip You should also be able to upgrade from the admin if it is not too broken right now

**Comment by unclescooby** [comment]
Thanks. Took some time on this end as well. Was able to view the admin by copy-pasting css styles from another installation via browser dev tools. Update worked fine and css issue is now fixed. Thanks!
