### ISSUE TITLE
Deprecate the RSS and atom feed code

### ISSUE THREAD

**Issue by markkap** [calmPress/calmpress#31]
Seems like neither chrome nor edge ever supported showing RSS feeds, and now firefox is going to deprecate them as well which relegates them to the area of server to server communication, which is a niche.

The only use case that I have encountered was using RSS feed to populate mailchimp based newsletter, but even there the current feed generated lacks all the required attributes, namely featured image.

This should be deprecated from core and move into a core plugin if there is any demand at all.

**Comment by mikeschinkel** [comment]
Core plugin, definitely.

**Comment by markkap** [comment]
The main use case for `fetch_feed` outside of core is to grab plugin and theme "news stream". I have a feeling that no user will actually miss it, but need to create a stub for the function if the core plugin is not loaded to prevent errors in this case.

"all in one event calendar" seems to be the most challenging in this regard as it directly uses the simple_pie APIs, so might need a stub for it as well. Hmm, looks like wptouch also needs it, SEO ultimate, and probably some others.

**Comment by markkap** [comment]
After the feed related deprecations of #242, #243 and #244, we are left with "post" feeds in RSS2 and ATOM format.

Decided to move only the ATOM feed to its own core plugin and leave the RSS2 feed in place, just adding an option to turn it off. The reason for keeping RSS feeds as part of the core is that some external services like MailChimp make use of it and it might be non-trivial for users coming from WordPress land to understand that they need to look for a plugin to get such functionality.
OTOH ATOM, is just not a requirement for anything, and not being a default it is less likely that people will not need the feed, and the people that do are more likely to be willing to search for a plugin for it.

**Comment by markkap** [comment]
Going to use the feed size option - `posts_per_rss` to indicate when feeds are "off". A value of 0 in it will indicate that feeds are off. 

The "off" value will be set as the default value in new installs.

"feeds off" will mean that the rewrite rule for feeds is not there at all and there for the rules might need to be flushed when the option changes.

**Comment by markkap** [comment]
And the code for the atom feed plugin is at https://github.com/calmPress/atom-feeds
