### ISSUE TITLE
deprecate post formats

### ISSUE THREAD

**Issue by markkap** [calmPress/calmpress#82]
Post format suffer from a UX problem as it requires you to think in advance what kind of content you are creating, or check after publishing that you actually selected the right type. Add to that that no theme I know bothered to do anything interesting with that information and you get a feature that users reject.

The way it should have been done from the start is to have some automated algorithm that suggests a format based on analyzing the content, but there is nothing that prevent theme author from creating such an algorithm and adding the relevant UI to override it.

It does not seem like this feature has any real justification for being in core

**Comment by markkap** [comment]
As there might be some few sites that uses this feature we need to think of an upgrade path for them. For example maybe delay removing the taxonomy to the remote future to let information be reused for conversion, maybe a core plugin?

**Comment by mikeschinkel** [comment]
Please.  Can you have this done by last year?!? 
![image](https://user-images.githubusercontent.com/153285/47695910-b6248400-dbda-11e8-981c-ab41286532ee.png)

**Comment by markkap** [comment]
Leaving the internal related APIs located at wp-includes\post-formats.php in case there is any plugin or theme using them.

Further deprecation of those functions will be left for the future.
