### ISSUE TITLE
Authors should be a taxonomy and not being related to the user actually posting the content

### ISSUE THREAD

**Issue by markkap** [calmPress/calmpress#87]
For many sites the author information is not relevant at all as there is only one author. For many other (bigger) sites content is received as a "word" document and some "web master" use the CMS admin to publish it.
In other words, for many sites the author information as is used by WordPress is not helpful and in some cases just harmful (discloses the user name).

We are going to split the usage of author information as it being done by WordPress into two parts
1. Indicate who has the permission to edit the content
2. Front end indication of the actual author and ability to filter/search content by that criteria. This will be done by a dedicated taxonomy.

This will also solve the problem of multiple authors for the same content.

The breaking change here will be changes in the API, especially since themes and plugins are not expecting to have no authors or more than one author.

**Comment by markkap** [comment]
There are some permalink structure settings that are related to authors. Will need to look into what should be done there.

**Comment by markkap** [comment]
Probably need to add deprecation notice in the relevant author APIs

**Comment by mikeschinkel** [comment]
Definitely agree with this, as long as there is an option for the user to automatically sync the user with the author taxonomy when, for example, they are the only user for a small business site.

**Comment by markkap** [comment]
`wp_list_authors` got some reduction in the parameters that it accepts
- No feed related options
- Removal of user-specific sorting criteria, leaving only `name` (and `display_name` just in cases anyone used it anywhere) and `post_count`
- Excluding admin makes no sense now so it went away (not that it made sense or was written correctly before)

**Comment by markkap** [comment]
`get_author_feed_link` has gone away since it is almost not used by plugins and themes, which makes it pointless to add a relevant method to the author's interface and implementation, especially when taking into account the wish to get RSS out of core.
